DROP TABLE T_INITIAL_ZK
/
DROP TABLE T_IN_OUT_ZK
/
DROP TABLE T_LOCATION_MASTER_ZK
/
DROP TABLE T_PIC_MASTER_ZK
/
DROP TABLE T_PRODUCTS_ZK
/
DROP TABLE T_PRODUCT_MASTER_ZK
/
DROP TABLE T_DEBUG
/
DROP PACKAGE PKG_ZK_DEMO_APP
/
DROP PACKAGE PKG_DELETE_OLD_DATA
/
DROP PACKAGE PKG_ZK_DEMO_DRS
/
DROP SEQUENCE   T_IN_OUT_ZK_SEQ
/
DROP SEQUENCE   T_PIC_MASTER_ZK_SEQ
/
DROP SEQUENCE   T_PRODUCTS_ZK_SEQ
/
--過去データ削除JOB無効化
BEGIN
    DBMS_SCHEDULER.DISABLE('JOB_DELETE_OLD_DATA');
END;
/
--過去データ削除JOB削除
BEGIN
    DBMS_SCHEDULER.DROP_JOB('JOB_DELETE_OLD_DATA');
END;
/